all:
	@gcc -o p1 p1.c
	@gcc -o p2 p2.c
	@gcc -o p3 p3.c
	@gcc -o p4 p4.c
	@gcc -o p5 p5.c
	@gcc -o p6 p6.c
	@gcc -o simpleScheduler simpleScheduler.c

clean:
	@rm -f p1
	@rm -f p2
	@rm -f p3
	@rm -f p4
	@rm -f p5
	@rm -f p6
	@rm -f simpleScheduler